export const ERROR_CODES = {
  AVATAR_LOAD_FAILED: 'AVATAR_LOAD_FAILED',
  ANIMATION_PLAY_FAILED: 'ANIMATION_PLAY_FAILED',
  AUDIO_TTS_FAILED: 'AUDIO_TTS_FAILED',
  DIALOGUE_REQUEST_FAILED: 'DIALOGUE_REQUEST_FAILED',
  N8N_REQUEST_FAILED: 'N8N_REQUEST_FAILED',
  RAG_REQUEST_FAILED: 'RAG_REQUEST_FAILED',
  UPLOAD_VALIDATION_FAILED: 'UPLOAD_VALIDATION_FAILED',
  API_TIMEOUT: 'API_TIMEOUT',
  API_REQUEST_FAILED: 'API_REQUEST_FAILED',
  CONFIG_INVALID: 'CONFIG_INVALID',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  UNKNOWN: 'UNKNOWN'
};
