export const EVENT_NAMES = {
  APP_INIT: 'app:init',
  APP_READY: 'app:ready',
  STATE_CHANGED: 'state:changed',
  AVATAR_SWITCH_START: 'avatar:switch:start',
  AVATAR_SWITCH_COMPLETE: 'avatar:switch:complete',
  AVATAR_SWITCH_ERROR: 'avatar:switch:error',
  AVATAR_SELECTED: 'avatar:selected',
  AVATAR_LOADED: 'avatar:loaded',
  AVATAR_ERROR: 'avatar:error',
  INTERACTION_HIT: 'interaction:hit',
  ANIMATION_REQUEST: 'animation:request',
  ANIMATION_STATE: 'animation:state',
  ANIMATION_ACTION_START: 'animation:action:start',
  ANIMATION_ACTION_COMPLETE: 'animation:action:complete',
  ANIMATION_ERROR: 'animation:error',
  DIALOGUE_USER: 'dialogue:user',
  DIALOGUE_THINKING: 'dialogue:thinking',
  DIALOGUE_ASSISTANT: 'dialogue:assistant',
  DIALOGUE_RESPONSE: 'dialogue:response',
  DIALOGUE_ERROR: 'dialogue:error',
  AUDIO_REQUEST: 'audio:request',
  AUDIO_START: 'audio:start',
  AUDIO_END: 'audio:end',
  AUDIO_FALLBACK: 'audio:fallback',
  AUDIO_ERROR: 'audio:error',
  SYSTEM_ERROR: 'system:error'
};
